version: '3.8'

services:
  
  mongo:
    image: mongo  
    container_name: mongodb_for_qrchat
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo_ui
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo