version: '3.8'

services:
  
  mongo:
    image: mongo
    environment:
      PUID: 1000
      PGID: 1000
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: mongodb_for_qrchat
    ports:
      - "27017:27017"